// The 195 countries — Worldometers' list (193 UN member states + the two
// UN observer states, Holy See and State of Palestine). Continents follow the
// UN M49 geoscheme that list uses; "Latin America & Caribbean" + "Northern
// America" are split into North America (incl. Central America + Caribbean)
// and South America. tests/data.test.mjs pins the per-continent totals.
//
// Row: [ISO alpha-3, ISO numeric, display name, continent, ...search aliases]
// Single source of truth: read by the app at runtime and by tools/build-geo.mjs.
window.COUNTRIES = [
  ["AFG","004","Afghanistan","AS"],
  ["ALB","008","Albania","EU"],
  ["DZA","012","Algeria","AF"],
  ["AND","020","Andorra","EU"],
  ["AGO","024","Angola","AF"],
  ["ATG","028","Antigua and Barbuda","NA","Antigua","Barbuda"],
  ["ARG","032","Argentina","SA"],
  ["ARM","051","Armenia","AS"],
  ["AUS","036","Australia","OC"],
  ["AUT","040","Austria","EU","Österreich"],
  ["AZE","031","Azerbaijan","AS"],
  ["BHS","044","Bahamas","NA","The Bahamas"],
  ["BHR","048","Bahrain","AS"],
  ["BGD","050","Bangladesh","AS"],
  ["BRB","052","Barbados","NA"],
  ["BLR","112","Belarus","EU"],
  ["BEL","056","Belgium","EU"],
  ["BLZ","084","Belize","NA"],
  ["BEN","204","Benin","AF"],
  ["BTN","064","Bhutan","AS"],
  ["BOL","068","Bolivia","SA"],
  ["BIH","070","Bosnia and Herzegovina","EU","Bosnia","Herzegovina"],
  ["BWA","072","Botswana","AF"],
  ["BRA","076","Brazil","SA","Brasil"],
  ["BRN","096","Brunei","AS","Brunei Darussalam"],
  ["BGR","100","Bulgaria","EU"],
  ["BFA","854","Burkina Faso","AF"],
  ["BDI","108","Burundi","AF"],
  ["CPV","132","Cabo Verde","AF","Cape Verde"],
  ["KHM","116","Cambodia","AS","Kampuchea"],
  ["CMR","120","Cameroon","AF"],
  ["CAN","124","Canada","NA"],
  ["CAF","140","Central African Republic","AF","CAR"],
  ["TCD","148","Chad","AF"],
  ["CHL","152","Chile","SA"],
  ["CHN","156","China","AS","People's Republic of China","PRC"],
  ["COL","170","Colombia","SA"],
  ["COM","174","Comoros","AF"],
  ["COG","178","Congo","AF","Republic of the Congo","Congo-Brazzaville"],
  ["CRI","188","Costa Rica","NA"],
  ["CIV","384","Côte d'Ivoire","AF","Ivory Coast"],
  ["HRV","191","Croatia","EU","Hrvatska"],
  ["CUB","192","Cuba","NA"],
  ["CYP","196","Cyprus","AS"],
  ["CZE","203","Czechia","EU","Czech Republic"],
  ["COD","180","DR Congo","AF","Democratic Republic of the Congo","Congo-Kinshasa","Zaire"],
  ["DNK","208","Denmark","EU"],
  ["DJI","262","Djibouti","AF"],
  ["DMA","212","Dominica","NA"],
  ["DOM","214","Dominican Republic","NA"],
  ["ECU","218","Ecuador","SA"],
  ["EGY","818","Egypt","AF"],
  ["SLV","222","El Salvador","NA"],
  ["GNQ","226","Equatorial Guinea","AF"],
  ["ERI","232","Eritrea","AF"],
  ["EST","233","Estonia","EU"],
  ["SWZ","748","Eswatini","AF","Swaziland"],
  ["ETH","231","Ethiopia","AF"],
  ["FJI","242","Fiji","OC"],
  ["FIN","246","Finland","EU"],
  ["FRA","250","France","EU"],
  ["GAB","266","Gabon","AF"],
  ["GMB","270","Gambia","AF","The Gambia"],
  ["GEO","268","Georgia","AS"],
  ["DEU","276","Germany","EU","Deutschland"],
  ["GHA","288","Ghana","AF"],
  ["GRC","300","Greece","EU","Hellas"],
  ["GRD","308","Grenada","NA"],
  ["GTM","320","Guatemala","NA"],
  ["GIN","324","Guinea","AF"],
  ["GNB","624","Guinea-Bissau","AF"],
  ["GUY","328","Guyana","SA"],
  ["HTI","332","Haiti","NA"],
  ["HND","340","Honduras","NA"],
  ["HUN","348","Hungary","EU"],
  ["ISL","352","Iceland","EU"],
  ["IND","356","India","AS","Bharat"],
  ["IDN","360","Indonesia","AS"],
  ["IRN","364","Iran","AS","Persia"],
  ["IRQ","368","Iraq","AS"],
  ["IRL","372","Ireland","EU","Eire"],
  ["ISR","376","Israel","AS"],
  ["ITA","380","Italy","EU","Italia"],
  ["JAM","388","Jamaica","NA"],
  ["JPN","392","Japan","AS","Nippon"],
  ["JOR","400","Jordan","AS"],
  ["KAZ","398","Kazakhstan","AS"],
  ["KEN","404","Kenya","AF"],
  ["KIR","296","Kiribati","OC"],
  ["KWT","414","Kuwait","AS"],
  ["KGZ","417","Kyrgyzstan","AS","Kyrgyz Republic"],
  ["LAO","418","Laos","AS","Lao PDR"],
  ["LVA","428","Latvia","EU"],
  ["LBN","422","Lebanon","AS"],
  ["LSO","426","Lesotho","AF"],
  ["LBR","430","Liberia","AF"],
  ["LBY","434","Libya","AF"],
  ["LIE","438","Liechtenstein","EU"],
  ["LTU","440","Lithuania","EU"],
  ["LUX","442","Luxembourg","EU"],
  ["MDG","450","Madagascar","AF"],
  ["MWI","454","Malawi","AF"],
  ["MYS","458","Malaysia","AS"],
  ["MDV","462","Maldives","AS"],
  ["MLI","466","Mali","AF"],
  ["MLT","470","Malta","EU"],
  ["MHL","584","Marshall Islands","OC"],
  ["MRT","478","Mauritania","AF"],
  ["MUS","480","Mauritius","AF"],
  ["MEX","484","Mexico","NA","México"],
  ["FSM","583","Micronesia","OC","Federated States of Micronesia"],
  ["MDA","498","Moldova","EU"],
  ["MCO","492","Monaco","EU"],
  ["MNG","496","Mongolia","AS"],
  ["MNE","499","Montenegro","EU"],
  ["MAR","504","Morocco","AF"],
  ["MOZ","508","Mozambique","AF"],
  ["MMR","104","Myanmar","AS","Burma"],
  ["NAM","516","Namibia","AF"],
  ["NRU","520","Nauru","OC"],
  ["NPL","524","Nepal","AS"],
  ["NLD","528","Netherlands","EU","Holland"],
  ["NZL","554","New Zealand","OC","Aotearoa"],
  ["NIC","558","Nicaragua","NA"],
  ["NER","562","Niger","AF"],
  ["NGA","566","Nigeria","AF"],
  ["PRK","408","North Korea","AS","DPRK"],
  ["MKD","807","North Macedonia","EU","Macedonia"],
  ["NOR","578","Norway","EU"],
  ["OMN","512","Oman","AS"],
  ["PAK","586","Pakistan","AS"],
  ["PLW","585","Palau","OC"],
  ["PSE","275","Palestine","AS","State of Palestine"],
  ["PAN","591","Panama","NA","Panamá"],
  ["PNG","598","Papua New Guinea","OC","PNG"],
  ["PRY","600","Paraguay","SA"],
  ["PER","604","Peru","SA","Perú"],
  ["PHL","608","Philippines","AS"],
  ["POL","616","Poland","EU","Polska"],
  ["PRT","620","Portugal","EU"],
  ["QAT","634","Qatar","AS"],
  ["ROU","642","Romania","EU"],
  ["RUS","643","Russia","EU","Russian Federation"],
  ["RWA","646","Rwanda","AF"],
  ["KNA","659","Saint Kitts and Nevis","NA","St Kitts","Nevis"],
  ["LCA","662","Saint Lucia","NA","St Lucia"],
  ["VCT","670","Saint Vincent and the Grenadines","NA","St Vincent","Grenadines"],
  ["WSM","882","Samoa","OC"],
  ["SMR","674","San Marino","EU"],
  ["STP","678","São Tomé and Príncipe","AF"],
  ["SAU","682","Saudi Arabia","AS","KSA"],
  ["SEN","686","Senegal","AF"],
  ["SRB","688","Serbia","EU"],
  ["SYC","690","Seychelles","AF"],
  ["SLE","694","Sierra Leone","AF"],
  ["SGP","702","Singapore","AS"],
  ["SVK","703","Slovakia","EU"],
  ["SVN","705","Slovenia","EU"],
  ["SLB","090","Solomon Islands","OC"],
  ["SOM","706","Somalia","AF","Somaliland"],
  ["ZAF","710","South Africa","AF"],
  ["KOR","410","South Korea","AS","Korea","Republic of Korea"],
  ["SSD","728","South Sudan","AF"],
  ["ESP","724","Spain","EU","España"],
  ["LKA","144","Sri Lanka","AS","Ceylon"],
  ["SDN","729","Sudan","AF"],
  ["SUR","740","Suriname","SA"],
  ["SWE","752","Sweden","EU"],
  ["CHE","756","Switzerland","EU"],
  ["SYR","760","Syria","AS"],
  ["TJK","762","Tajikistan","AS"],
  ["TZA","834","Tanzania","AF","Zanzibar"],
  ["THA","764","Thailand","AS","Siam"],
  ["TLS","626","Timor-Leste","AS","East Timor"],
  ["TGO","768","Togo","AF"],
  ["TON","776","Tonga","OC"],
  ["TTO","780","Trinidad and Tobago","NA","Trinidad","Tobago"],
  ["TUN","788","Tunisia","AF"],
  ["TUR","792","Turkey","AS","Türkiye"],
  ["TKM","795","Turkmenistan","AS"],
  ["TUV","798","Tuvalu","OC"],
  ["UGA","800","Uganda","AF"],
  ["UKR","804","Ukraine","EU"],
  ["ARE","784","United Arab Emirates","AS","UAE","Emirates"],
  ["GBR","826","United Kingdom","EU","UK","Great Britain","Britain","England","Scotland","Wales","Northern Ireland"],
  ["USA","840","United States","NA","USA","US","America","United States of America"],
  ["URY","858","Uruguay","SA"],
  ["UZB","860","Uzbekistan","AS"],
  ["VUT","548","Vanuatu","OC"],
  ["VAT","336","Vatican City","EU","Holy See","Vatican"],
  ["VEN","862","Venezuela","SA"],
  ["VNM","704","Vietnam","AS","Viet Nam"],
  ["YEM","887","Yemen","AS"],
  ["ZMB","894","Zambia","AF"],
  ["ZWE","716","Zimbabwe","AF"],
];

window.CONTINENTS = {
  AF: "Africa", AS: "Asia", EU: "Europe",
  NA: "North America", SA: "South America", OC: "Oceania",
};

// Territories: real, distinct, inhabited places that are NOT among the 195
// (Worldometers/UN-recognized sovereign states) but are commonly and genuinely
// "visited" as their own place. Included if it (a) has its own ISO 3166-1 code
// — official, or for Kosovo the widely-used unofficial XK/XKX — distinct from
// any of the 195, (b) has a real permanent civilian population, and (c) is
// large enough to render (a shape or a dot) from what's already on the map.
// Excluded under the same rule (no permanent population / restricted access):
// British Indian Ocean Territory, French Southern & Antarctic Lands, Heard &
// McDonald Islands, Siachen Glacier, South Georgia. Svalbard is a real gap —
// Natural Earth 50m doesn't draw it separately from Norway at this detail
// level, so there's no geometry to attach it to.
// Row: [iso3, isoNumeric(null — matched to geometry by name, not code), name, continent, ...aliases]
window.TERRITORIES = [
  ["ASM", null, "American Samoa", "OC"],
  ["AIA", null, "Anguilla", "NA"],
  ["ABW", null, "Aruba", "NA"],
  ["BMU", null, "Bermuda", "NA"],
  ["VGB", null, "British Virgin Islands", "NA", "BVI"],
  ["BES", null, "Caribbean Netherlands", "NA", "Bonaire", "Sint Eustatius", "Saba"],
  ["CYM", null, "Cayman Islands", "NA"],
  ["CXR", null, "Christmas and Cocos Islands", "OC", "Christmas & Cocos Islands", "Christmas Island", "Cocos Islands", "Cocos Keeling Islands"],
  ["COK", null, "Cook Islands", "OC"],
  ["CUW", null, "Curaçao", "NA"],
  ["FLK", null, "Falkland Islands", "SA", "Malvinas"],
  ["FRO", null, "Faroe Islands", "EU"],
  ["GUF", null, "French Guiana", "SA"],
  ["PYF", null, "French Polynesia", "OC", "Tahiti", "Bora Bora"],
  ["GRL", null, "Greenland", "NA"],
  ["GLP", null, "Guadeloupe", "NA"],
  ["GUM", null, "Guam", "OC"],
  ["GGY", null, "Guernsey", "EU"],
  ["HKG", null, "Hong Kong", "AS"],
  ["IMN", null, "Isle of Man", "EU"],
  ["JEY", null, "Jersey", "EU"],
  ["XKX", null, "Kosovo", "EU"],
  ["MAC", null, "Macao", "AS", "Macau"],
  ["MTQ", null, "Martinique", "NA"],
  ["MYT", null, "Mayotte", "AF"],
  ["MSR", null, "Montserrat", "NA"],
  ["NCL", null, "New Caledonia", "OC"],
  ["NIU", null, "Niue", "OC"],
  ["NFK", null, "Norfolk Island", "OC"],
  ["MNP", null, "Northern Mariana Islands", "OC", "Saipan"],
  ["PCN", null, "Pitcairn Islands", "OC"],
  ["PRI", null, "Puerto Rico", "NA"],
  ["REU", null, "Réunion", "AF"],
  ["BLM", null, "Saint Barthélemy", "NA", "St Barts", "St Barths"],
  ["SHN", null, "Saint Helena", "AF"],
  ["MAF", null, "Saint Martin", "NA"],
  ["SPM", null, "Saint Pierre and Miquelon", "NA"],
  ["SXM", null, "Sint Maarten", "NA"],
  ["TWN", null, "Taiwan", "AS"],
  ["TCA", null, "Turks and Caicos Islands", "NA"],
  ["VIR", null, "U.S. Virgin Islands", "NA", "USVI"],
  ["WLF", null, "Wallis and Futuna", "OC"],
  ["ESH", null, "Western Sahara", "AF"],
  ["ALA", null, "Åland", "EU", "Aland", "Aland Islands"],
  ["SJM", null, "Svalbard and Jan Mayen", "EU", "Svalbard", "Spitsbergen", "Jan Mayen", "Longyearbyen"],
];
